"""
Modular tool definitions for the Google ADK Sight-Reading Composer Agent.
Each function is an ADK-ready tool that can be used by agents or orchestration pipelines.
"""
from typing import Dict, Any, Optional
from app.utils.abc_validator import clean_and_validate_abc


def validate_abc_score_tool(
    raw_abc: str,
    default_title: str = "Sight-Reading Exercise",
    default_key: str = "C",
    default_meter: str = "4/4",
    default_tempo: int = 110,
    expected_bars: int = 4,
    instrument: Optional[str] = None,
    difficulty: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Validates and cleans raw ABC notation output, enforcing required measure counts,
    instrument pitch range constraints, and removing any trills or ornamentation (TR skill).

    Args:
        raw_abc: Raw string generated by the composer model.
        default_title: Fallback T: title header.
        default_key: Fallback K: key signature header.
        default_meter: Fallback M: time signature header.
        default_tempo: Fallback Q: tempo header.
        expected_bars: Expected number of measures in the score.
        instrument: Target instrument (e.g. saxophone, flute, violin, piano, guitar, cello).
        difficulty: Target difficulty level (beginner, intermediate, advanced, expert).

    Returns:
        dict: Result containing is_valid, cleaned_abc, error_message, and expected_bars.
    """
    is_valid, clean_abc, err = clean_and_validate_abc(
        raw_abc=raw_abc,
        default_title=default_title,
        default_key=default_key,
        default_meter=default_meter,
        default_tempo=default_tempo,
        expected_bars=expected_bars,
        instrument=instrument,
        difficulty=difficulty,
    )

    return {
        "is_valid": is_valid,
        "cleaned_abc": clean_abc,
        "error_message": err,
        "expected_bars": expected_bars,
        "instrument": instrument,
        "difficulty": difficulty,
    }
